# This workflow will do a clean installation of node dependencies, build the source code and run tests across different node versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # See supported pnpm versions and compatibility at https://pnpm.io/installation#compatibility
        include:
          - node: 18.6
            pnpm: 8
          - node: 20
            pnpm: 10
          - node: 22
            pnpm: 10
          - node: 24
            pnpm: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm ${{ matrix.pnpm }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}
          run_install: false

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test
