# This workflow will run tests using node and then publish a package to GitHub Packages when a release is published
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish Package
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      
      - name: Clean install
        run: npm ci
      
      - name: Run tests
        run: npm run test
      
      - name: Build package
        run: npm run build
      
      - name: Publish to jsr
        run: npx jsr publish
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
